SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} obtained HM01\n"
    .string "from the CAPTAIN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "This move is useless honestly,\n"
    .string "since the government has been\p"
    .string "keeping the weeds clear.$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPTAIN: …Whew!\p"
    .string "Now that I'm not sick anymore,\n"
    .string "I guess it's time.\p"
    .string "The S.S. ANNE will set sail soon!\p"
    .string "Farewell, until our return to\n"
    .string "VERMILION CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "Oh, no!\n"
    .string "You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "How to Conquer Seasickness…\n"
    .string "The CAPTAIN's reading this!$"

