Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, pal.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, lady.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Wait till I get inside the\n"
    .string "TELEPORTER.\p"
    .string "When I do, go to my PC and run\n"
    .string "the Cell Separation System.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, chief?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, beautiful?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"

Route25_SeaCottage_Text_ObtainedAnEevee::
    .string "{PLAYER} obtained an EEVEE!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Thanks, bud! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You can check my favorites\n"
    .string "out on my PC if you want!\p"
    .string "Since it looks like you're\n"
    .string "a trainer, maybe this'll do\p"
    .string "as thanks. It's my fav.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Thanks, lady! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You can check my favorites\n"
    .string "out on my PC if you want!\p"
    .string "Since it looks like you're\n"
    .string "a trainer, maybe this'll do\p"
    .string "as thanks. It's my fav.$"

Route25_SeaCottage_Text_SSAnneParty::
    .string "There's a cruise ship in\n"
    .string "VERMILION CITY.\p"
    .string "I hear there are lots of TRAINERS\n"
    .string "on board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Feel like checking out some\n"
    .string "of my rare POKéMON on my PC?\p"
    .string "Go on, check out my PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILL's favorite POKéMON list!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Which POKéMON do you want to see?$"

